[package]
name = "hdr-snipping-tool"
version = "1.2.0"
authors = ["Trent Shailer <trent.shailer@gmail.com>"]
edition = "2021"

build = "build.rs"

[dependencies]
arboard = "3.3.0"
chrono = { version = "0.4.33", default-features = false, features = ["clock"] }
fern = "0.6.2"
glium = { version = "0.32.1", default-features = true }
image = { version = "0.24.8", default-features = false, features = ["png"] }
imgui = "0.11.0"
imgui-glium-renderer = "0.11.0"
imgui-winit-support = "0.11.0"
livesplit-hotkey = "0.7.0"
log = "0.4.20"
owo-colors = "4.0.0"
rayon = "1.8.1"
serde = { version = "1.0.196", features = ["derive"] }
snafu = "0.8.0"
toml = "0.8.9"
tray-icon = "0.11.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52.0", features = [
	"Foundation",
	"Graphics_Capture",
	"Graphics_DirectX_Direct3D11",
	"Win32_Foundation",
	"Win32_Graphics_Direct3D_Fxc",
	"Win32_Graphics_Direct3D11",
	"Win32_Graphics_Dxgi_Common",
	"Win32_Graphics_Gdi",
	"Win32_Security",
	"Win32_System_Threading",
	"Win32_System_WinRT_Direct3D11",
	"Win32_System_WinRT_Graphics_Capture",
	"Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
embed-resource = "2.4"

[profile.release]
lto = true
