[package]
name = "hdr-capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
fern = "0.6.2"
image = { version = "0.24.8", features = ["rayon"] }
copypasta = "0.8"
glium = { version = "0.32.1", default-features = true }
imgui = "0.11.0"
imgui-glium-renderer = "0.11.0"
imgui-winit-support = "0.11.0"
inputbot = "0.6.0"
log = "0.4.20"
owo-colors = "4.0.0"
rayon = "1.8.1"
windows = { version = "0.52.0", features = [
	"Foundation",
	"Win32_Foundation",
	"Win32_UI_WindowsAndMessaging",
	"Win32_System_Console",
	"Win32_Graphics_Dwm",
	"Win32_Graphics_Gdi",
	"Win32_Graphics_Dxgi",
	"Win32_Graphics_Dxgi_Common",
	"Win32_Graphics_Direct3D_Fxc",
	"Win32_Graphics_Direct3D",
	"Win32_Graphics_Direct3D11",
	"Win32_System_WinRT",
	"Win32_System_WinRT_Direct3D11",
	"Win32_System_WinRT_Graphics_Capture",
	"UI",
	"Storage",
	"Storage_Streams",
	"Graphics",
	"Graphics_Capture",
	"Graphics_DirectX",
	"Graphics_DirectX_Direct3D11",
	"Graphics_Imaging",
] }
arboard = "3.3.0"

[profile.release]
lto = true
