[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
half = { version = "2.4", features = ["bytemuck"] }
log = "0.4"
smallvec = "1.13"
thiserror = "1.0"
vulkano = { version = "0.34" }
vulkano-shaders = { version = "0.34" }
windows = { version = "0.57" }
windows-core = { version = "0.57" }
windows-result = { version = "0.1" }
winit = { version = "0.30", default-features = false }

vulkan-instance = { path = "crates/vulkan-instance" }
vulkan-renderer = { path = "crates/vulkan-renderer" }
vulkan-tonemapper = { path = "crates/vulkan-tonemapper" }
windows-capture-provider = { path = "crates/windows-capture-provider" }
