[package]
name = "vulkan-instance"
version = "1.4.0"
edition = "2021"

[dependencies]
log = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
vulkano = { workspace = true }
winit = { workspace = true }
