[package]
name = "vulkan-instance"
version = "3.0.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
vulkano = { workspace = true }
winit = { workspace = true }
