[package]
name = "hdr-capture"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkan-instance = { workspace = true }
windows-capture-provider = { workspace = true }

ash = { workspace = true }
thiserror = { workspace = true }
half = { workspace = true }
tracing = { workspace = true }
