[package]
name = "vulkan-renderer"
version = "1.2.1"
edition = "2021"

[dependencies]
vulkan-instance = { workspace = true }

fontdue = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
vulkano = { workspace = true }
vulkano-shaders = { workspace = true }
winit = { workspace = true }
