[package]
name = "vulkan-renderer"
version = "2.0.0"
edition = "2021"

[dependencies]
vulkan-instance = { workspace = true }

tracing = { workspace = true }
thiserror = { workspace = true }
winit = { workspace = true }
ash = { workspace = true }
