[package]
name = "hdr-snipping-tool"
version = "1.4.0"
edition = "2021"

build = "build.rs"

[dependencies]
hdr-capture = { path = "../hdr-capture" }
gamma-compression-tonemapper = { path = "../gamma-compression-tonemapper" }

arboard = "3.3.0"
chrono = { version = "0.4.33", default-features = false, features = ["clock"] }
fern = "0.6.2"
glow = "0.12.0"
glutin = "0.31.3"
glutin-winit = "0.4.2"
image = { version = "0.24.8", default-features = false, features = ["png"] }
imgui = "0.11.0"
imgui-glow-renderer = "0.11.0"
livesplit-hotkey = "0.7.0"
log = "0.4.20"
owo-colors = "4.0.0"
raw-window-handle = "0.5.0"
serde = { version = "1.0.196", features = ["derive"] }
snafu = "0.8.0"
toml = "0.8.9"
tray-icon = "0.11.2"
winit = { version = "0.29.13", features = ["rwh_05"] }


[target.'cfg(windows)'.dependencies]
windows-hdr-capture-provider = { path = "../windows-hdr-capture-provider" }
windows = { version = "0.52.0", features = [
	"Foundation",
	"Graphics_Capture",
	"Win32_Foundation",
	"Win32_Security",
	"Win32_System_Threading",
] }

[build-dependencies]
embed-resource = "2.4"
