[package]
name = "gamma-compression-tonemapper"
version = "1.4.0"
edition = "2021"

[dependencies]
imgui = { version = "0.11.0", optional = true }

rayon = "1.9.0"
hdr-capture = { path = "../hdr-capture" }

[features]
imgui = ["hdr-capture/imgui-settings-renderer", "dep:imgui"]
